name: Update Visits

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/15 * * * *" # Runs every 15 minutes

jobs:
  update_visits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          known_hosts: "just_accept" # 不太安全，但简化了设置。 生产环境中，添加主机密钥

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Increment visit counter
        id: increment
        run: |
          if [ ! -f visits.txt ]; then echo "0" > visits.txt; fi
          visits=$(cat visits.txt)
          visits=$((visits + 1))
          echo $visits > visits.txt
          echo "::set-output name=visits::$visits"

      - name: Update README.md
        run: |
          visits=${{ steps.increment.outputs.visits }}
          badge="![Visits](https://img.shields.io/badge/Visits-23455-blue)"
          sed -i 's|!\[Visits\](https://img.shields.io/badge/Visits-.*-blue)|'"$badge"'|' README.md

      - name: Commit and push changes
        run: |
          git add visits.txt README.md
          git commit -m 'Update visits count'
          git push origin main # 或你想要推送的分支名
